gradio:
  flagging_dir: "flagged"
  allow_flagging: "auto"
  share: False
  questions: "questions.json"
llama_index:
  data_dir: "data_10k"
  persist_dir: "storage"
  embedding_model: "text-embedding-3-small"
  llm_model: "gpt-3.5-turbo"
  temperature: 0
  chunk_size: 512
  similarity_top_k: 3
  streaming: True
chroma_db:
  path: "./chroma_db_10k"
  collection: "hepth"
